* (yet another) emacs mode for quarto
=poly-quarto= is loosely based on [[https://github.com/quarto-dev/quarto-emacs][quarto-emacs]] mode and aims at
editing [[https://quarto.org/][quarto]] documents.
** Installation
1. Install [[https://polymode.github.io/installation/][polymode]]
2. Download (or clone) =poly-quarto.el= and put it in your emacs
      directory (for example the directory
      =/home/foouser/.emacs.d/lisp= or  =/home/foouser/.config/emacs/lisp=)
3. To use poly-quarto mode, add the following to your
      =.emacs= or =.emacs.d/init.el= or =.config/emacs/init.el=
      #+begin_src emacs-lisp
      (load "/home/foouser/.emacs.d/lisp/poly-quarto.el")
      (require 'polymode)
      (require 'poly-quarto)
      #+end_src
** Philosophy
=poly-quarto= mode use code from [[https://github.com/quarto-dev/quarto-emacs][quarto-emacs]] and [[https://github.com/polymode/poly-markdown][poly-markdown]] to implement quarto mode based on [[https://github.com/polymode/poly-markdown][polymode]].
It (tries to) offers
- direct support of quarto through [[https://github.com/polymode/poly-markdown][polymode]] without relying on
   [[https://github.com/polymode/poly-markdown][poly-markdown]] (and [[https://github.com/polymode/poly-markdown][polymode]]),
- div/pandoc block inner mode for such blocks:
  #+begin_src
::: {#mytag name="Myname"}

:::
  #+end_src
  and outline support for it:
  Hit =<TAB>= on =::: {#mytag name="Myname"}= to hide/show, ie outline,
- better(?) LaTeX support (see section below),
- integration with ispell (it skips code blocks).
** LaTeX support
*** Using poly-quarto
1. Use =poly-quarto-insert-align-block= or =C-M-a= to insert displayed equation to
   have LaTeX block as
   #+begin_src
$$%
\begin{align*}
x&=2
\end{align*}
$$
   #+end_src
2. If you import some code without this convention use  =poly-quarto-fix-latex-delimiters=
    to fix LaTeX delimiters:
   - it will replace
     #+begin_src
$$
\begin{align*}
x=2
\end{align*}
$$

$$
y=3
$$
     #+end_src
     by
     #+begin_src
$$%
\begin{align*}
x&=2
\end{align*}
$$

$$%
y&=3
$$
     #+end_src
   - and also math environments =eqnarray= =align= =equation= without LaTeX delimiters like
     #+begin_src
\begin{align*}
x&=2
\end{align*}
     #+end_src
     by math environment with LaTeX delimiters like
     #+begin_src
$$%
\begin{align*}
x&=2
\end{align*}
$$
     #+end_src
     The list of math environments without LaTeX delimiters is by
     default =eqnarray= =align= =equation=
     but it can be customized using custom
     variable =poly-quarto-latex-delims=.
*** Inline and displayed formula problem
To start math formulas in LaTeX there is a long standing use of =$$ ... $$=
or =$ ... $= even it is preferable to use =\[ ... \]= or =\( ... \)=.
This kind of delimiters are "symmetric" (the same delimiter denotes
beginning and end of sequence) and it does not play well with polymode.
To circumvent this problem poly-quarto enforces the use of non-symmetric
delimiters:

- for displayed formula
  #+begin_src
$$%
...
$$
  #+end_src
  or
  #+begin_src
\[
...
\]
  #+end_src
  Inside these delimiters polymode will use indirect buffers and
  this like a "tex" file: it is advised to begin math environment
  between these delimiters (even if quarto does not care) in order
  to keep latex-mode happy: for instance if
  you use =amsmath= you can insert a latex block
  (=poly-quarto-insert-align-block= or =C-M-a=) as follows
   (other math environments are obviously possible):
  #+begin_src
$$%
\begin{align*}
x&=2
\end{align*}
$$
  #+end_src
  or classical/base LaTeX:
  #+begin_src
\[
\begin{eqnarray*}
x&=&2
\end{eqnarray*}
\]
  #+end_src
- for inline formula
  #+begin_src
bla bla $x=2$, but $y=3$ and $z=4$.
  #+end_src
  or
  #+begin_src
bla bla \(x=2\), but \(y=3\) and \(z=4\).
  #+end_src
After the last =$= in inline formula =$...$= above, there must be a
punctuation sign (=.,;:!?=) or a "real" space
or space equivalent (=~\n\t=). As this is a quite usual
way to use inline formula it will be hopefully unnoticed.
** Useful functions
- =poly-quarto-fix-latex-delimiters= try to fix LaTeX delimiters in order to have only non symmetric delimiters
- =poly-quarto-insert-align-block= insert latex block with math =align*= environment at point (bound to =C-M-a=)
- =poly-quarto-insert-latex-block= insert latex block without math environment at point (bound to =C-M-l=)
- =poly-quarto-insert-inline-code= insert code chunk (src block, code block) at point (bound to =C-M-i=). Use =poly-quarto-set-lang= to set language (default to =r=)
- =poly-quarto-set-lang=: Change language (choices are given in custom variable =poly-quarto-all-codelang=)
- =poly-quarto-send-chunk= Send the whole code chunk  (bound to =C-c C-c=)
- inside a code chunk (or code block or src block): all functions and bindings are provided by the mode of code chunk (for instance in R, all ess-r-mode functions and bindings)
- inside a LaTeX block all functions and bindings are provided by LaTeX-mode (or latex-mode).
- inside a LaTeX block all functions and bindings are provided by LaTeX-mode (or latex-mode).
** Font-lock
Font-lock does not work well inside doom emacs. If you are annoyed you can
re-fontify the buffer entirely (=poly-quarto-fontify-current-buffer=)
or around point (=poly-quarto-fontify-around-point= bound to =C-M-f=)

** "TODO List"
- [ ] cleaning preview/export
- [ ] adding xref support for label/ref
